<?php
/**
 * Hook into page preprocess to add
 * navigation links to title suffix
 *
 * @param array $variables
 *
 * @return void
 */
function flat_collection_navigation_preprocess_page(&$variables) {

    // arg(3) === null means we are on the view page
    if (arg(0) === 'islandora' && arg(3) === null) {

        module_load_include('inc', 'flat_collection_navigation', 'includes/NavigationLinksGenerator');

        $generator       = new NavigationLinksGenerator();
        $navigationLinks = $generator->generate(arg(2));

        if (false !== $navigationLinks) {

            if (!isset($variables['title_suffix']['#markup'])) {
                $variables['title_suffix']['#markup'] = '';
            }

            $variables['title_suffix']['#markup'] = '<div style="margin-bottom: 10px; ">' . implode(' | ', $navigationLinks) . '</div>' . $variables['title_suffix']['#markup'];
        }
    }
}
